# -*- coding: utf-8 -*-
"""program32.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T_QPzRquDXS0h9hzT_gYF71FWaJHnE4l
"""

n=int(input("Enter the number of students:"))
studlist=[]
for i in range(0,n):
  stud={}
  stud['name']=input("Enter name:\n")
  stud["branch"]=input("Enter branch:\n")
  stud["roll no"]=int(input("Enter roll no:\n"))
  studlist.append(stud)
print("Name  Branch  Roll no")
print()
print()
for i in range(0,n):  
  print(studlist[i])