# -*- coding: utf-8 -*-
"""program31.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1njRXRcjrl643w-J3SBQxu3wka0sRRwcN
"""

stud={}
n=int(input("Enter the no. of students:"))
for i in range(0,n):
  a=input("Enter the name of student:")
  stud[a]=int(input("Enter the mark of student:"))
print(stud)
b=[]
b+=stud.keys()
b.sort()
for i in range(n):
  print("%s\t\t\t%d" %(b[i],stud[b[i]]))