# -*- coding: utf-8 -*-
"""program17

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dg3UZt2pyx-HKaZuDnn7Gg2ANWl3Ft17
"""

def fib(n):
        a = 0
        b = 1
        for i in range(2,n):
            c = a+b
            print(c)
            a = b
            b =c

n = int(input("Enter the number:"))
if n==1:
    print(0)
elif n==2:
    print(0,1)
else:
    print(0)
    print(1)
    fib(n)